apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: scrapyd-k8s
  name: scrapyd-k8s
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: scrapyd-k8s
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scrapyd-k8s
    spec:
      serviceAccountName: scrapyd-k8s
      containers:
        - image: ghcr.io/q-m/scrapyd-k8s:main # TODO latest when published
          imagePullPolicy: IfNotPresent
          name: scrapyd-k8s
          ports:
            - containerPort: 6800
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
          livenessProbe:
            failureThreshold: 30
            httpGet:
              path: /
              port: http
          resources:
            limits:
              memory: 128Mi # TODO check
            requests:
              memory: 64Mi # TODO check
          volumeMounts:
            - mountPath: /opt/app/scrapyd_k8s.conf
              name: scrapyd-k8s-config
              readOnly: true
              subPath: scrapyd_k8s.conf
      volumes:
        - configMap:
            name: scrapyd-k8s-config
          name: scrapyd-k8s-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scrapyd-k8s-config
  labels:
    app.kubernetes.io/name: scrapyd-k8s
data:
  scrapyd_k8s.conf: |-
    [scrapyd]
    bind_address = 0.0.0.0
    http_port    = 6800

    repository   = scrapyd_k8s.repository.Remote
    launcher     = scrapyd_k8s.launcher.K8s

    namespace    = scrapyd

    # adapt the spider config to your use-case
    [project.example]
    env_secret   = spider-example-env
    repository   = ghcr.io/example-org/example-spider
---
apiVersion: v1
kind: Secret
metadata:
  name: spider-example-env
  labels:
    app.kubernetes.io/name: spider-example
stringData:
  FOO_API_KEY: 1234567890abcdef
---
apiVersion: v1
kind: Service
metadata:
  name: scrapyd-k8s
  labels:
    app.kubernetes.io/name: scrapyd-k8s
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 6800
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/name: scrapyd-k8s
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scrapyd-k8s
  namespace: scrapyd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scrapyd-k8s
  namespace: scrapyd
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scrapyd-k8s
  namespace: scrapyd
subjects:
  - kind: ServiceAccount
    name: scrapyd-k8s
roleRef:
  kind: Role
  name: scrapyd-k8s
  apiGroup: rbac.authorization.k8s.io
