name: Tests on Docker
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Pull example spider
        run: docker pull ghcr.io/q-m/scrapyd-k8s-spider-example

      - name: Run scrapyd-k8s
        run: |
          cp scrapyd_k8s.sample-docker.conf scrapyd_k8s.conf
          python -m scrapyd_k8s &
          while ! nc -q 1 localhost 6800 </dev/null; do sleep 1; done
          curl http://localhost:6800/daemonstatus.json

      - name: Run tests
        run: pytest -vv test_api.py
